//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NewVision.rc
//
#define IDR_FILE                        1
#define IDS_WAIT                        2
#define IDD_ABOUTBOX                    3
#define IDP_OLE_INIT_FAILED             4
#define IDD_MYPROPERTYPAGE              5
#define IDD_FILECAMERA                  6
#define IDD_TRACKER                     7
#define IDD_BACKGROUNDDIALOG            8
#define IDD_BLOBDIALOG                  9
#define IDB_NEWPROJECTBG                10
#define IDD_BODYDIALOG                  11
#define IDD_FINISH                      12
#define IDD_DOORDIALOG                  13
#define IDD_CALIBRATEDIALOG             14
#define IDD_SELECTCAMERA                15
#define IDD_FLOORDIALOG                 16
#define IDD_OBSTACLEDIALOG              17
#define IDD_PROGRESS                    18
#define IDD_PROGRESS_DIALOG             18
#define IDB_TOOLBAR_TC                  19
#define IDB_BITMAP2                     20
#define IDB_TOOLBAR_GR                  21
#define IDB_TOOLBAR_TC_HOT              22
#define IDI_ICON1                       23
#define IDI_UNINSTALL                   24
#define IDR_MENU_DISPLAY                25
#define IDD_TRACKTOOLBAR                27
#define IDD_SKINDIALOG                  28
#define IDD_ACTIVITYDIALOG              29
#define IDD_BODYACTIVITYDIALOG          29
#define IDD_RECORD_DIALOG               30
#define IDD_CONTROL_TOOLBAR             31
#define IDD_MESSAGEDIALOG               32
#define IDB_CUBOID                      33
#define IDD_BODYACTIVITYDIALOG1         33
#define IDD_SWARMACTIVITYDIALOG         33
#define IDB_POLYHEDRON                  34
#define IDB_CYLINDER                    35
#define ID_AUX_INDICATOR                122
#define ID_MEM_INDICATOR                123
#define ID_FRAME_INDICATOR              124
#define IDR_MAINFRAME                   125
#define IDR_SMILEY                      126
#define IDR_SETTINGS                    127
#define IDR_MENU_SETTINGS               129
#define IDDS_PROXIMITYEVENTDETECTOR     130
#define IDDS_GROUPINGEVENTDETECTOR      131
#define IDDS_LEADERFOLLOWINGEVENTDETECTOR 132
#define IDDS_LININGUPEVENTDETECTOR      133
#define IDDS_CODWELLINGEVENTDETECTOR    134
#define IDD_BLENDTOOLBAR                135
#define IDD_ZONEDIALOG                  136
#define IDR_MENU_BODY                   137
#define IDDS_BODYPRIORSTAB              138
#define IDD_ZOOM_TOOLBAR                139
#define IDD_ZOOMTOOLBAR                 139
#define IDDS_BODYTRACKINGTAB            141
#define IDI_MEN                         142
#define IDI_MEN1                        143
#define IDI_BALLS                       144
#define IDI_ICON2                       145
#define IDC_FLIP                        1000
#define IDC_MINERRTOCREATE              1001
#define IDC_ERODE                       1002
#define IDC_MAXVIEWS                    1003
#define IDC_DILATE                      1004
#define IDC_RADIOFILE                   1005
#define IDC_VIEWUPDATESPEED             1006
#define IDC_RADIOPGRFILE                1006
#define IDC_RADIOCAMERA                 1007
#define IDC_RADIOCAMERA2                1008
#define IDC_RADIOTHERMALCOLORPAIR       1009
#define IDC_SOURCENAME                  1011
#define IDC_FILESELECTBUTTON            1012
#define IDC_SOURCENAMET                 1012
#define IDC_SOURCESELECTBUTTON          1013
#define IDC_CAMERANUMBER                1014
#define IDC_SOURCESELECTBUTTONT         1014
#define IDC_CAMERASELECTBUTTON          1015
#define IDC_SRCWIDTH                    1016
#define IDC_FRAMERATE                   1017
#define IDC_SRCHEIGHT                   1018
#define IDC_SRCCHANNELS                 1019
#define IDC_FEATUREHISTOGRAM            1020
#define IDC_FEATUREHEIGHT               1021
#define IDC_FEATUREVELOCITY             1022
#define IDC_LISTDOORS                   1023
#define IDC_FEATUREWIDTH                1024
#define IDC_FEATUREPOSITION             1025
#define IDC_BUTTONDOORREMOVE            1026
#define IDC_FEATUREHEIGHT_S             1027
#define IDC_UPDATESPEED                 1028
#define IDC_FEATURESIZE                 1029
#define IDC_FEATUREWIDTH_S              1030
#define IDC_THRESHHIGH                  1031
#define IDC_CDMAX                       1032
#define IDC_THRESHLOW                   1033
#define IDC_BDMIN                       1034
#define IDC_INITFORNFRAMES              1035
#define IDC_IMAGE                       1036
#define IDC_THERMALMIN                  1036
#define IDC_MINIMUMAREA                 1037
#define IDC_SKIPNFRAMES                 1038
#define IDC_FLOOR                       1039
#define IDC_MAXIMUMAREA                 1040
#define IDC_BDMAX                       1041
#define IDC_BUTTONRESET                 1042
#define IDC_THERMALMAX                  1042
#define IDC_DETECTAFTERNFRAMES          1043
#define IDC_BDMAX2                      1043
#define IDC_BGSENSITIVITY               1043
#define IDC_BUTTONCOMPUTE               1044
#define IDC_MAXBODIES                   1045
#define IDC_TRACKAFTERPERCENTAGE        1046
#define IDC_MINMERGEDIST                1047
#define IDC_ERODESIZE                   1048
#define IDC_MAXDISTTOMATCH              1049
#define IDC_DILATESIZE                  1050
#define IDC_MAXERRORTOMATCH             1051
#define IDC_BUTTONADD                   1052
#define IDC_MINRAYSIZE                  1053
#define IDC_CLEANSTALEEVERY             1054
#define IDC_MAXERRORTOCOLORMATCH        1055
#define IDC_BUTTONDELETE                1056
#define IDC_STALECUTOFF                 1057
#define IDC_BLOBSBINS                   1058
#define IDC_TRACKAFTERAGE               1059
#define IDC_BUTTONDELETEALL             1060
#define IDC_BLOBHBINS                   1061
#define IDC_HEIGHTS                     1062
#define IDC_MINAGE                      1063
#define IDC_CURRENTHEIGHT               1064
#define IDC_PDELETE                     1065
#define IDC_UPDATEFREQ                  1066
#define IDC_MEASUREMENTNOISE            1067
#define IDC_POSMEASUREMENTNOISE         1068
#define IDC_RESET                       1069
#define IDC_ORIENTMEASUREMENTNOISE      1070
#define IDC_RADIOLEARNING               1071
#define IDC_RADIODYNAMIC                1072
#define IDC_TEXTDYN1                    1073
#define IDC_TEXTDYN2                    1074
#define IDC_TEXTDYN3                    1075
#define IDC_TEXTLEARNING1               1076
#define IDC_EDIT1                       1077
#define IDC_EDIT_XML_FILE               1077
#define IDC_FRAMESTART                  1078
#define IDC_WIDTHS                      1079
#define IDC_FRAMESTOP                   1079
#define IDC_ELEVATION                   1080
#define IDC_FLOORW                      1081
#define IDC_TEXTDYN4                    1082
#define IDC_COMBOCAMERANAME             1083
#define IDC_WIDTHM                      1084
#define IDC_FLOORH                      1085
#define IDC_WIDTHMAX                    1086
#define IDC_RECORD1                     1087
#define IDC_WIDTHMIN                    1088
#define IDC_RECORD2                     1089
#define IDC_DOORIMAGE                   1090
#define IDC_ITERATIONS                  1091
#define IDC_RECORD3                     1092
#define IDC_HEIGHTM                     1093
#define IDC_BUTTONFLOORREMOVE           1094
#define IDC_HEIGHTMAX                   1095
#define IDC_FLOORIMAGE                  1096
#define IDC_SKINIMAGE2                  1097
#define IDC_HISTOGRAMIMAGE              1098
#define IDC_COMPUTE_BODIES              1099
#define IDC_COMPUTE_BG                  1100
#define IDC_HEIGHTMIN                   1101
#define IDC_COLORIMAGE                  1102
#define IDC_COMPUTE_SWARMACTIVITIESS    1103
#define IDC_COMPUTE_BODYACTIVITIES      1103
#define IDC_RADIOFLOORIMAGE             1104
#define IDC_COMPUTE_SWARMACTIVITIESS2   1104
#define IDC_COMPUTE_SWARMACTIVITIES     1104
#define IDC_COMPUTE_HEATMAP             1105
#define IDC_SPATIOTEMPORAL              1106
#define IDC_PNONE                       1107
#define IDC_PROGRESS_BAR                1108
#define IDC_BODYOVERLAP                 1108
#define IDC_SWARM                       1109
#define IDC_OBSTACLEOVERLAP             1109
#define IDC_CUBOID                      1110
#define IDC_BODYMINDISTANCE             1110
#define IDC_COMPUTE_BODIES2             1111
#define IDC_RADIOFLOORCAD               1112
#define IDC_POLYHEDRON                  1113
#define IDC_PNEW                        1114
#define IDC_MESSAGE                     1115
#define IDC_PROGRESS_TEXT               1115
#define IDC_CYLINDER                    1116
#define IDC_FLOORNAME                   1117
#define IDC_PDISTANCE                   1118
#define IDC_FLOOR_VIEW                  1119
#define IDC_MESSAGES                    1120
#define IDC_FLOORMODELSELECTBUTTON      1121
#define IDC_BUTTONMESSAGEREMOVE         1122
#define IDC_PHEIGHT                     1123
#define IDC_PWIDTH                      1124
#define IDC_POBJECT                     1125
#define IDC_PBG                         1126
#define IDC_PABNORMAL                   1127
#define IDC_PABNORMALW                  1128
#define IDC_MODELNOISE                  1129
#define IDC_POSMODELNOISE               1130
#define IDC_ADD                         1131
#define IDC_REMOVE                      1132
#define IDC_ESTABLISH                   1133
#define IDC_PABNORMALH                  1134
#define IDC_BREAK                       1135
#define IDC_ORIENTMODELNOISE            1136
#define IDC_EXCHANGE                    1137
#define IDC_UPDATE                      1138
#define IDC_DIFFUSE                     1139
#define IDC_RANDOMNESS                  1140
#define IDC_BUTTONGETPATHDISTANCES      1141
#define IDC_SATURATIONTIME              1141
#define IDC_DOORDISTANCE                1142
#define IDC_PFG                         1143
#define IDC_MAXHISTCHANGE               1143
#define IDC_PROXIMITYDISTANCETHRESHOLD  1144
#define IDC_MAXPOSCHANGE                1144
#define IDC_DISTANCECONFIDENCE          1145
#define IDC_SALESREPTHRESHOLD           1146
#define IDC_MAXDELETEDAGE               1146
#define IDC_HYPERLINK                   1147
#define IDC_MAXDELETEDDIST              1147
#define IDC_ITERATIONS_PER_BODY         1148
#define IDC_PATHSMOOTHSIGMA             1149
#define IDC_FLOOR_SCROLLBAR1            1150
#define IDC_INVISIBLEFOR                1151
#define IDC_DWELLTIME                   1152
#define IDC_FLOOR_SCROLLBAR2            1153
#define IDC_OUTSIDERFOR                 1154
#define IDC_DWELLAREARADIUS             1155
#define IDC_CAMERA_SCROLLBAR2           1156
#define IDC_DORMANTFOR                  1157
#define IDC_CAMERA_SCROLLBAR1           1158
#define IDC_PROXIMITYMATUREPATH         1159
#define IDC_CAMERA_MONO                 1160
#define IDC_PROXIMITYTIMEDELTA          1161
#define IDC_RADIO2                      1162
#define IDC_CAMERA_PANO                 1163
#define IDC_DOORS_POINTS                1164
#define IDC_CAMERA_XML_FILE             1164
#define IDC_FRAME_VIEW                  1165
#define IDC_PROXIMITYEVERYNFRAME        1166
#define IDC_DOORS_INTEREST_REGION       1167
#define IDC_STATIC4                     1168
#define IDC_DOORS_INTEREST_REGION2      1168
#define IDC_DOORS_INTEREST_BOUNDARY     1168
#define IDC_STATIC3                     1169
#define IDC_DOORS_COUNTER               1169
#define IDC_STATIC1                     1170
#define IDC_DOOR_SCROLLBAR1             1171
#define IDC_DOOR_SCROLLBAR2             1172
#define IDC_BUTTONOBSTACLEREMOVE        1173
#define IDC_OBSTACLEIMAGE               1174
#define IDC_OBSTACLE_SCROLLBAR1         1175
#define IDC_OBSTACLE_SCROLLBAR2         1176
#define IDC_DOORS_UNIFORM               1177
#define IDC_STARTDATE                   1178
#define IDC_STARTTIME                   1179
#define IDC_RECORD_INPUT_VIEW           1180
#define IDC_RECORD_OUTPUT_VIEW          1181
#define IDC_SKINIMAGE                   1182
#define IDC_RECORD_FLOOR_VIEW           1183
#define IDC_BUTTONCLEAR                 1184
#define IDC_RECORD_ACTIVITY_VIEW        1185
#define IDC_SKIN_2DHISTORGAM            1186
#define IDC_SKIN_SCROLLBAR2             1187
#define IDC_SKIN_SCROLLBAR1             1188
#define IDC_SWARMACTIVITYTAB            1189
#define IDC_PROXIMITY                   1190
#define IDC_GROUPING                    1191
#define IDC_GROUPINGEVERYNFRAME         1191
#define IDC_LEADERFOLLOWING             1192
#define IDC_GROUPINGFITNESSTHRESHOLD    1192
#define IDC_TRACKING_MODE               1192
#define IDC_GROUPINGGROUPRADIUS         1193
#define IDC_HEATMAP_MODE                1193
#define IDC_LININGUP                    1194
#define IDC_GROUPINGCOHESIONW           1194
#define IDC_ACTIVITY_MODE               1194
#define IDC_CODWELLING                  1195
#define IDC_GROUPINGALIGNMENTW          1195
#define IDC_PLAYBACK_MODE               1195
#define IDC_GROUPINGDWELLW              1196
#define IDC_ACTT1                       1197
#define IDC_ACTT2                       1198
#define IDC_NEWVISIONVERSION            1199
#define IDC_GROUPINGITERATION0          1199
#define IDC_SLIDER                      1200
#define IDC_NEWVISIONVERSION2           1200
#define IDC_NEWVISIONBUILDDATETIME      1200
#define IDC_GROUPINGMAXCLUSTERS         1200
#define IDC_BUTTONDETECTNOW             1201
#define IDC_GROUPINGMINNODECARDINALITY  1201
#define IDC_ZONEIMAGE                   1202
#define IDC_GROUPINGEVENTSBEFOREFAME    1202
#define IDC_BUTTONZONEREMOVE            1203
#define IDC_GROUPINGMINEVENTWEIGHT      1203
#define IDC_ZONE_SCROLLBAR2             1204
#define IDC_GROUPINMINCARDINALITY       1204
#define IDC_ZONE_SCROLLBAR1             1205
#define IDC_GROUPINGMINACTORWEIGHT      1205
#define IDC_BUTTONZONEFROMOBSTACLE      1206
#define IDC_GROUPINMINCARDINALITY2      1206
#define IDC_GROUPINAGGLOMERATIONSPEED   1206
#define IDC_BUTTONZONENEW               1207
#define IDC_ZONE_FRAME_VIEW             1208
#define IDC_GROUPINGMAXOBJECTIVEFUNCTIONDELTA 1208
#define IDC_ZONE_FLOOR_VIEW             1209
#define IDC_GROUPINGMAXCLUSTERS2        1209
#define IDC_GROUPINGMAXITERATIONS       1209
#define IDC_BODYTAB                     1210
#define IDC_ZOOMSLIDER                  1211
#define ID_ZOOM                         1213
#define ID_SAVE_FILTER_GRAPH            1214
#define IDC_SAVE_FILTER_GRAPH           1214
#define IDC_USECOLOR                    1215
#define IDC_BUTTON_BROWSE_XML_FILE      1216
#define IDC_STATIC_XML_FILE             1217
#define IDC_HELPTEXT                    1218
#define ID_BACKGROUND                   33000
#define ID_BLOB                         33001
#define ID_PLAYPAUSE                    33002
#define ID_FILE                         33003
#define ID_CAMERA                       33004
#define ID_BACKGROUND_SETTINGS          33005
#define ID_BACKGROUND_LOAD              33006
#define ID_BACKGROUND_SAVE              33007
#define ID_BODY                         33008
#define ID_FILE_NEWPROJECT              33009
#define ID_FILE_OPENPROJECT             33010
#define ID_FILE_SAVEPROJECT             33011
#define ID_SETTINGS                     33012
#define ID_DOORS                        33013
#define ID_SETTINGS_SHOWHISTOGRAMS      33014
#define ID_SETTINGS_SHOWVIEWS           33015
#define ID_SETTINGS_RECORD              33016
#define ID_SETTINGS_PARAMETERS          33017
#define ID_BUTTON32803                  33018
#define ID_BUTTON32805                  33019
#define ID_BUTTON32806                  33020
#define ID_BUTTON32807                  33021
#define ID_BUTTON32808                  33022
#define ID_BUTTON32809                  33023
#define ID_PAUSE                        33024
#define ID_RECORD2                      33025
#define ID_RECORD                       33026
#define ID_STOP                         33027
#define ID_PLAY                         33028
#define ID_SLIDER                       33029
#define ID_SCROLLER                     33029
#define ID_POSITION                     33030
#define ID_INITTRACKER                  33031
#define ID_BUTTON32821                  33032
#define ID_BUTTON32822                  33033
#define ID_BUTTON32828                  33034
#define ID_BUTTON32829                  33035
#define ID_BUTTON32830                  33036
#define ID_BUTTON32831                  33037
#define ID_BUTTON32832                  33038
#define ID_BUTTON32833                  33039
#define ID_BUTTON32834                  33040
#define ID_DISPLAYPROPERTIES_LEFTPANEL  33041
#define ID_DISPLAYPROPERTIES_RIGHTPANEL 33042
#define ID_VIDEOPANEL_BLOBS             33043
#define ID_Menu                         33045
#define ID_SCENEPANEL_BODIES            33046
#define ID_SCENEPANEL_BLOBS             33047
#define ID_SCENEPANEL_GROUPS            33048
#define ID_SCENEPANEL_PATHS             33049
#define ID_HELP_ABOUT                   33050
#define ID_VIDEOPANEL_BODIES            33051
#define ID_SCENEPANEL_BACKGROUND        33052
#define ID_SCENEPANEL_CAMERA            33053
#define ID_SCENEPANEL_DOORS             33054
#define ID_ACTIVITYPANEL_SALESREPS      33055
#define ID_ACTIVITYPANEL_DWELLINGBODIES 33056
#define ID_FLOORPANEL_FLOORMAP          33057
#define ID_FLOORPANEL_BODYMAPS          33058
#define ID_FLOORPANEL_BODYPATHS         33059
#define ID_FLOORPANEL_HEATMAP           33060
#define ID_FLOORPANEL_OBSTACLES         33061
#define ID_DATA_SAVEHEATMAP             33062
#define ID_DATA_SAVEFLOORVIEW           33063
#define ID_DATA_SAVEINPUTVIEW           33064
#define ID_DATA_SAVEOUTPUTVIEW          33065
#define ID_FLOORPANEL_TIMESTAMP         33066
#define ID_VIDEOPANEL_TIMESTAMP         33067
#define ID_ACTIONS_LEFTCLICK            33068
#define ID_LEFTCLICK_MOVEBODY           33069
#define ID_LEFTCLICK_MARK_SALES_PERSON  33070
#define ID_DATA_SAVETRACKINGDATA        33071
#define ID_DATA_LOADTRACKINGDATA        33072
#define ID_PLAY_RECORDED_TRACKING_DATA  33073
#define ID_VIDEOPANEL_BODYHEIGHTS       33074
#define ID_VIDEOPANEL_BLOBHEIGHTS       33075
#define ID_SCENEPANEL_HISTOGRAMS        33076
#define ID_VIDEOPANEL_DOORS             33077
#define ID_VIDEOPANEL_OBSTACLES         33079
#define ID_ACTION_GOTOFRAME             33080
#define ID_GOTOFRAME                    33081
#define ID_ACTION_GOTOTIME              33084
#define ID_GOTOTIME                     33085
#define ID_VIDEOPANEL_INPUTIMAGE        33086
#define ID_DATA_LOADACTIVITYDATA        33087
#define ID_DATA_SAVEACTIVITYDATA        33088
#define ID_DATA_LOADHEATMAPDATA         33089
#define ID_DATA_SAVEHEATMAPDATA         33090
#define ID_DATA_SAVESCREEN              33091
#define ID_DATA_LOADDATA                33092
#define ID_DATA_SAVEDATA                33093
#define ID_Menu33094                    33094
#define ID_BODY_EDITINFO                33095
#define ID_BODY_MOVE                    33096
#define ID_BODY_CHANGEID                33097
#define ID_BODY_DELETE                  33098
#define ID_SETTINGS_NEWVISIONSETTINGS   33099
#define ID_BODY_SWAPIDS                 33102
#define ID_SCENEPANEL_Z                 33103
#define ID_VIEW_SPLITWINDOW             33104
#define ID_VIEW_TABS                    33105
#define ID_VIEW_SPLITSCRENN             33106
#define ID_VIEW_SPLITSCREEN             33107
#define ID_BODY_TERMINATETRACK          33108
#define ID_BODY_TERMINATE               33109
#define ID_SCENEPANEL_DISTANCEPLANE     33110
#define ID_ACTIVITYPANEL_GROUPS         33114
#define ID_ACTIVITYPANEL_SWARMS         33115
#define ID_ACTIVITYPANEL_BODIES         33116
#define ID_SAVESCREEN_ACTIVITYVIEW      33117
#define ID_DATA_SAVEACTIVITYVIEW        33118
#define ID_VIEW_TRACKS                  33119
#define ID_BODY_EDITINFOID              33122
#define ID_BODY_MERGE                   33123
#define ID_BODY_MERGEID                 33124
#define ID_BODY_APPEND                  33125
#define ID_BODY_APPENDID                33126
#define ID_FLOORPANEL_BODYTRACKS        33132
#define ID_ACTION_SETPLAYBACKRATE       33133
#define ID_SETPLAYBACKRATE              33134
#define ID_VIEW_FULLSCREEN              33135
#define ID_BUTTON33136                  33136
#define ID_ACCELERATOR33137             33137
#define ID_DATA_VISUALIZE               33139
#define ID_VISUALIZEDATA_TRACKS         33140
#define ID_VISUALIZEDATA_HEATMAP        33141
#define ID_BODY_ADDTOGROUP              33142
#define ID_VIEW_GROUPS                  33145
#define ID_ACTION_BACK1FRAME            33146
#define ID_ACTION_FWD1FRAME             33147
#define ID_ACTION_BACK1FRAME33148       33148
#define ID_ACTION_FWD10FRAMES           33149
#define ID_REW1                         33150
#define ID_FFW1                         33151
#define ID_REW10                        33152
#define ID_FFW10                        33153
#define ID_REW5                         33154
#define ID_FFW5                         33155
#define ID_UPDATE_BG                    33157
#define ID_DATA_DETECTGROUPS            33158
#define ID_VISUALIZEDATA_MOTION         33159
#define ID_VISUALIZEDATA_X3DROLLERCOASTER 33160
#define ID_VISUALIZEDATA_DWELLHEATMAP   33161
#define ID_DATA_FILTERGROUPS            33165
#define ID_ACTIVITY_DETECTEVENTS        33166
#define ID_ACTIVITY_DETECTGROUPS        33167
#define ID_ACTIVITY_FILTERGROUPS        33168
#define ID_VIDEOPANEL_BODYORIENTATIONS  33172
#define ID_VIDEOPANEL_ORIENTATIONS      33173
#define ID_ACTIVITY_FILTERGROUPS2       33174
#define ID_FLOORPANEL_ZONES             33175
#define ID_BODY_SETASDEFAULT            33176
#define ID_VISUALIZEDATA_TIMETAGS       33180

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         33181
#define _APS_NEXT_CONTROL_VALUE         1219
#define _APS_NEXT_SYMED_VALUE           1289
#endif
#endif
